In [2]:
import csv
from bs4 import BeautifulSoup

In [11]:


import pandas as pd

df1 = pd.read_csv("../data/wuzzuf_jobs.csv", encoding="utf-8")
df2 = pd.read_csv("../data/indeed_listings.csv", encoding="utf-8")
df3 = pd.read_csv("../data/Linkedin_listings.csv", encoding="utf-8")


df2.head()

,job_id,job_url,search_keyword,title,company,location,salary,job_type,date,description,error
0,e8c53d08b2ec3652,https://eg.indeed.com/viewjob?jk=e8c53d08b2ec3652,software engineer,Machine Learning Engineer,Smart Eye AB,NaN,NaN,NaN,NaN,Industry\n\n\nElectronics & Components\n\n\n\n...,NaN
1,e04833b6aea6d2f2,https://eg.indeed.com/viewjob?jk=e04833b6aea6d2f2,software engineer,IT Manager (Desktop Support),Confidential,NaN,"EGP 55,000 - EGP 80,000 a month",NaN,NaN,The \nDesktop Support Manager\n is responsible...,NaN
2,021caa024cbbe01e,https://eg.indeed.com/viewjob?jk=021caa024cbbe01e,software engineer,AI/Machine Learning Engineer | Hybrid,Rawaj - Human Capital Management,NaN,NaN,NaN,NaN,"We are seeking passionate, forward-thinking pr...",NaN
3,f5af78b7fe9bf7d5,https://eg.indeed.com/viewjob?jk=f5af78b7fe9bf7d5,software engineer,Reservoir Engineer - Customer Success - EOR (H...,Tachyus,NaN,NaN,NaN,NaN,We are looking for a Petroleum Engineer to wor...,NaN
4,881633ba7b84887d,https://eg.indeed.com/viewjob?jk=881633ba7b84887d,software engineer,AI Tech Pre-sales,SDG Group,NaN,NaN,NaN,NaN,Transform the Future with SDG: Global Leaders ...,NaN

In [12]:
newdf = pd.DataFrame(
    {
        "url": pd.concat([ df1["job_url"],df2["job_url"],df3["job_url"] ], ignore_index=True),
        "title" :  pd.concat([ df1["title"],df2["title"],df3["job_title"] ], ignore_index=True),
        "company" :  pd.concat([ df1["company_name"],df2["company"],df3["company_name"] ], ignore_index=True),
        "job_type": pd.concat([ df1["job_type"] , pd.Series([None] * len(df2)) , df3["seniority_level"] ], ignore_index=True),
        "employment_type":  pd.concat([ pd.Series([None] * len(df1)), pd.Series([None] * len(df2)), df3["employment_type"] ], ignore_index=True),
        "description" :  pd.concat([ df1["description"],df2["description"],df3["description"] ], ignore_index=True),
        "requirements":  pd.concat([ df1["requirements"] , pd.Series([None] * len(df2)) ,  pd.Series([None] * len(df3)) ] , ignore_index=True),
    }
)

In [13]:
newdf.head()

,url,title,company,job_type,employment_type,description,requirements
0,https://wuzzuf.net/jobs/p/20aaef26-36bf-4ca9-b...,Senior .NET Software Engineer,Teaspoon,job,None,"<p>At <strong>Teaspoon</strong>, we’re not jus...",<p><strong>Must-Have Skills</strong></p><ul><l...
1,https://wuzzuf.net/jobs/p/1a76629c-cd4d-4f10-9...,Software Engineer Intern,Avidbeam Technologies,internship,None,<p><strong>Job Description:</strong><br><br>A ...,"<ul><li>Senior Graduates in Computer Science, ..."
2,https://wuzzuf.net/jobs/p/df1b4288-20c9-4575-8...,Software Engineer,NaN,job,None,<p>Are you a budding software enthusiast ready...,"<ul><li>Bachelor's degree in Computer Science,..."
3,https://wuzzuf.net/jobs/p/360d7493-9fd4-40b1-b...,Senior Software Quality Assurance Engineer,FirstTech,job,None,<ul><li>Coordinate with product managers and d...,<p>Qualifications</p><ul><li>Bachelor's degree...
4,https://wuzzuf.net/jobs/p/66b4beff-08d1-4278-8...,Software Engineer (Technical Content),"CC Global Group, LLC",job,None,<p><strong>About Codecontent</strong><br><stro...,<p><strong>Required Qualifications</strong><br...

In [14]:
newdf.tail()

,url,title,company,job_type,employment_type,description,requirements
4051,https://www.linkedin.com/jobs/view/4404503542/,"Cairo University, Engineering, Career Day - 22...",Air Liquide,Not Applicable,Full-time,How will you CONTRIBUTE and GROW?\nThank You f...,None
4052,https://www.linkedin.com/jobs/view/4404564290/,Computer Vision Engineer (PyTorch/TensorRT),Flatgigs,Not Applicable,Full-time,We are seeking a Computer Vision Engineer with...,None
4053,https://www.linkedin.com/jobs/view/4362963235/,Computer Vision Engineer (PyTorch/TensorRT),Flatgigs,Entry level,Full-time,We are seeking a Computer Vision Engineer with...,None
4054,https://www.linkedin.com/jobs/view/4399984021/,Computer Vision Engineer,Summit Technology Solutions,Associate,Full-time,Key Responsibilities\nFine-tune pre-trained OC...,None
4055,https://www.linkedin.com/jobs/view/4293413577/,"ETIC, Python & Django Software Engineer-Manager",PwC,Mid-Senior level,Full-time,Line of Service\nAdvisory\nIndustry/Sector\nTe...,None

In [71]:
newdf.to_csv("merged_jobs.csv", index=False, encoding="utf-8")

In [15]:

# simple cleaning
def clean_html(text):
    return BeautifulSoup(str(text), "html.parser").get_text(" ", strip=True)

newdf["description"] = newdf["description"].apply(clean_html)
newdf["requirements"] = newdf["requirements"].apply(clean_html)

newdf = newdf.fillna('') 

text_cols = ['title', 'company', 'description', 'requirements']
for col in text_cols:
    newdf[col] = newdf[col].str.strip()

In [84]:

newdf.to_csv("merged_jobs_clean.csv", index=False, encoding="utf-8-sig")

In [19]:
empty_count = (newdf["requirements"] == "").sum()
print(empty_count)

2